default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: carwow
  password: carwow

development:
  <<: *default
  database: hackergames2018_development
test:
  <<: *default
  database: hackergames2018_test

production:
  <<: *default
  database: hackergames2018_production
  username: hackergames2018
  password: <%= ENV['HACKERGAMES2018_DATABASE_PASSWORD'] %>
